services:
  coredns01:
    image: docker.io/coredns/coredns:latest
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./Corefile:/Corefile:ro
    networks:
      dnstap-network:
        ipv4_address: 172.16.10.10
  coredns02:
    image: docker.io/coredns/coredns:latest
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./Corefile:/Corefile:ro
    networks:
      dnstap-network:
        ipv4_address: 172.16.10.11
  netshoot:
    image: docker.io/nicolaka/netshoot:latest
    tty: true
    networks:
      - dnstap-network
    volumes:
      - /etc/localtime:/etc/localtime:ro
  dnstap:
    build:
      context: ./build_dnstap-receiver-kafka
      dockerfile: Containerfile
    networks:
      - dnstap-network
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dnstap.conf:/app/dnstap.conf:ro
    depends_on:
      - kafka
  kafka:
    image: docker.io/apache/kafka:4.0.1
    networks:
      dnstap-network:
        ipv4_address: 172.16.10.20
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_NUM_PARTITIONS=3

networks:
  dnstap-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.10.0/24
          gateway: 172.16.10.1